### ISSUE TITLE
PECL Redis missing from composer dependencies

### ISSUE THREAD

**Issue by mashiox** [openthc/common#1]
I noticed `OpenTHC\Service\Redis` makes use of the `\Redis` class, and after looking at the usage of `\Redis`'s interface, I believe it's PECL Redis class. 

Common's composer configuration is missing the `ext-redis` requirement. I have a project that is dependent on `OpenTHC\Service\Redis` and did not have the `php7.4-redis` package installed. When I used the library's `Redis::factory` method, I would get a PHP fatal error because it could not find the `\Redis` class.

When I added the `ext-redis` requirement to my project's composer configuration and then ran composer update, I was able to get a fatal error from composer because the redis extension was not installed.

I then installed the pecl redis extension on my system for PHP 7.4, and re-ran the composer update. After this, composer was able to complete updating. And my script could make use of the `OpenTHC\Service\Redis` class.

**Comment by djbusby** [comment]
Fixed in 8bcc9d8
