### ISSUE TITLE
getProvider assumes too much

### ISSUE THREAD

**Issue by mashiox** [openthc/common#6]
The configuration it uses is not enough to tell which client is in use at the time `getProvider` is executed. https://github.com/openthc/common/blob/master/lib/Controller/Auth/oAuth2.php#L37-L73

We need to add a `setClient` method that sets the client id and client secret as a class parameter. And use that everywhere in our apps with the client's configuration information.

We can still use the SSO config in `getProvider` method, because we still need to know the SSO `origin`.

**Comment by djbusby** [comment]
These issues were mostly caused by poorly defined options in the configuration files and inconsistent usage of them.  The fields in the configuration files have been updated and the code in getProvider is now using these updated configuration properties.
